default_title: Webdeveloper and Search Engine Optimizer | Wesley Smits
meta_description: Wesley Smits is a front-end web developer and SEO based in Holland. He creates websites for local businesses and helps them perform well in search engines.
