fabriq = Project.create([{name: 'Fabriq', description: 'Dit is Fabriq'}])
butzi = Project.create([{name: 'Butzi', description: 'Dit is Butzi'}])
vicinity = Project.create([{name: 'Verkeersschool-Vicinity', description: 'Dit is Verkeersschool-Vicinity'}])
approxiv = Project.create([{name: 'Approxiv', description: 'Dit is Approxiv'}])
marauders = Project.create([{name: 'Marauders', description: 'Dit is Marauders'}])
tord = Project.create([{name: 'Truth or Dare', description: 'Dit is Truth or Dare'}])